version: "3.8"
services:
  db:
    image: mysql:8.0.19
    container_name: mysql_container
    restart: on-failure
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--max_connections=10000",
      ]
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123
    volumes:
      - /data/dockerVolume/mysql-data:/var/lib/mysql
    ports:
      - "0.0.0.0:3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 1024M
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-padmin123"]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 4000
      CORS_ORIGIN: http://localhost:5173
      JWT_SECRET: supersecret_jwt_key_change_me
      JWT_EXPIRES_IN: 1d
      #DB_HOST: localhost
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: portfolio_db
      DB_USER: root
      DB_PASSWORD: admin123
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "0.0.0.0:4000:4000"
    volumes:
      - ./backend:/app
    # extra_hosts:
    # - "host.docker.internal:host-gateway"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE_URL: http://localhost:4000
    ports:
      - "0.0.0.0:5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  db_data:
